hubblo-org/scaphandre

- docs/exporters/stdout.md
- src/exporters/stdout.rs
@bpetit, please let me know if you want a different description or switches.
Error handling is maybe a bit brutal by making a panic if the value passed is not a numeric one.
> Add step_duration option to stdout exporter (issue #27)

- init.sh
- Follow shellcheck advises. In particular:
https://github.com/koalaman/shellcheck/wiki/SC2044
- Use strict mode.
- Use read only vars.
- Add a short usage.
- Use explicit functions
- Some stuffs are not useful now, but may help later.
> Make init.sh more robust

- .gitignore
- src/sensors/powercap_rapl.rs
- src/sensors/utils.rs
- tests/integration.rs
@bpetit, I wish you a happy new year ! :tada: 
* All tests and doctests should now run fine using `cargo test`.
* No more warning as well.
* Remove few "dead code".
* Create integration_tests directory if it does not exist.
_Note: as I changed a little the doctests, documentation needs to be regenerated and pushed if needed._
So `cargo test` is fully clean. Even if it is a little thing, I like this because it gives some kind of confidence on the project to new comers
```
running 15 tests
test sensors::tests::get_proc_cpuinfo ... ok
test sensors::tests::read_socket_stats ... ok
test sensors::tests::read_topology_stats ... ok
test sensors::units::tests::joule_equals_1000000microjoules ... ok
test sensors::units::tests::joule_to_milijoules ... ok
test …
```
> fix: Latest failed tests

- docs/exporters/prometheus.md
- src/exporters/mod.rs
- src/exporters/prometheus.rs
- src/exporters/stdout.rs
- src/main.rs
The prometheus exporter --qemu option extract vmname and expose it.
> feat: Add --qemu option to prometheus exporter

- .github/workflows/build-and-test.yml
- Cargo.toml
- docs_src/SUMMARY.md
- docs_src/references/exporter-json.md
- src/exporters/json.rs
- src/exporters/mod.rs
- src/lib.rs
- src/main.rs
Add JSON reporter.
You can use the following options:
- -t to customize the timeout
- -s to customize the interval
- -f to change the destination file where to write the report
If no file is provided, then the JSON is displayed in the console.
If the directory where to create the file does not exist it will fail.
TODO:
- interval should be in milliseconds or should at least allows sending float number.
- documentation
> feat: add json reporter

- src/sensors/powercap_rapl.rs
this is about https://github.com/hubblo-org/scaphandre/issues/55
> fix: allowing scaph to run even if intel_rapl modules r not found

- Cargo.toml
Bump version to the updated riemann-client. (https://github.com/borntyping/rust-riemann_client/pull/6 and https://github.com/borntyping/rust-riemann_client/pull/7)
- Bump riemann client to 0.9.0
- Bump protobuff to 2.20.0
> feat: Bump dependencies version

- sample-stack/docker-compose.yaml
- sample-stack/grafana/Dockerfile
- sample-stack/grafana/dashboards.yml
- sample-stack/grafana/datasource.yml
- sample-stack/grafana/sample-dashboard.json
- sample-stack/prom/Dockerfile
- sample-stack/prom/prometheus.yml
This is a simple docker-compose stack that run in a single step scaphandre along preconfigured instances of prometheus and grafana. resolve hubblo-org/scaphandre#53
Things that should be done before merging:
> Basic example stack

- src/exporters/json.rs
Signed-off-by: Jérémie Drouet <jeremie.drouet@gmail.com>
> refacto(json): convert for loops to iterators

- docs_src/README.md
- docs_src/compatibility.md
- docs_src/contributing.md
- docs_src/explanations/how-scaph-computes-per-process-power-consumption.md
Hi, fixed a broken link to _Explanations_ section on doc home page + minor typos.
> docs: fixing dead link and typos

- helm/scaphandre/templates/rbac.yaml
- helm/scaphandre/values.yaml
@bpetit This adds support for the `--containers arg` to the helm chart.
It also extends the RBAC rules for listing pods.
> feat: add support for containers arg to helm chart

- Dockerfile
Use latest Ubuntu in docker file as a proposed fix for https://github.com/hubblo-org/scaphandre/issues/150
Alternative could also be to use an older LTS version.
_After merge, docker image may need to be republished as `hubblo/scaphandre:latest`_
> fix: use ubuntu 20.04 LTS in docker image

- src/sensors/utils.rs
Fixes the container to pod lookup when kubeadm is using the systemd cgroup driver.
https://kubernetes.io/docs/tasks/administer-cluster/kubeadm/configure-cgroup-driver/
> fix: Support kubelets using systemd cgroup driver

- helm/scaphandre/templates/psp.yaml
Hi,  
We tried installing scaphandre on our cluster (baremetal, kubespray, 1.22, docker) using helm and the pods were not being created due to invalid PSP configuration.  
After some investigation, we found out that the daemonset used a `projected` volume and that `projected` volumes were not allowed by the PSP. Adding `projected` volume to the PSP fixes the installation.  
This PR adds `projected` to the list of volumes allowed by the PSP created by Helm
> Fix missing volume in psp

- .github/dependabot.yml
- Setup dependabot for Rust by adding `dependabot.yml` file in the Github configuration
- Weekly frequency to have up-to-date Rust dependencies
- Only on `dev` branch
refers to #180 
https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file
> Add dependabot Github file for Rust dependencies

- src/sensors/mod.rs
Hello, while trying to use scaphandre with the qemu I encountered the issue #133. Looking into it a bit more, the reason behind this stems from the way qemu (at least for my setup) handles multi-core/multi-thread CPUs. In essence, instead of allowing you to set core or thread count for the virtual CPU, you add sockets to the VM; see this [stack overflow discussion](https://superuser.com/questions/1577756/qemu-cpu-topology-doesn-t-match-maximum-vcpu-count).  
So to fix this I just fall back to the first socket found by the sensor and add all encountered cores to it. Sorry if the code is ugly, I'm new to rust. Anyway, with this fix, u can use the VM mode even for VM's with more vCores.
> Addressed issue #133

- docs_src/tutorials/kubernetes.md
- helm/scaphandre/templates/servicemonitor.yaml
- helm/scaphandre/values.yaml
Allow configuration of service monitor in order to have metrics collected by an external prometheus
Signed-off-by: Nicolas Trangosi <nicolas.trangosi@dcbrain.com>
> feat: Add service monitor on helm chart

- helm/scaphandre/templates/psp.yaml
- helm/scaphandre/templates/rbac.yaml
@bpetit This is a fix for https://github.com/hubblo-org/scaphandre/issues/246 
I opened it against main but LMK if I should be targeting dev 🙏
> fix: Don't create PSP if k8s >= 1.25

- .github/workflows/build-and-test.yml
- .github/workflows/codesee-arch-diagram.yml
- .github/workflows/python_build.yml
- Cargo.lock
- Cargo.toml
- src/exporters/json.rs
- src/exporters/mod.rs
- src/exporters/prometheus.rs
- src/exporters/qemu.rs
- src/exporters/riemann.rs
- src/exporters/stdout.rs
- src/exporters/warpten.rs
- src/lib.rs
- src/main.rs
- src/sensors/mod.rs
- src/sensors/msr_rapl.rs
- src/sensors/powercap_rapl.rs
- src/sensors/utils.rs
- tests/integration.rs
This PR mainly **removes code**. It's a refactoring of how exporters are created.
Instead of using `Arg::new` and passing a `Vec<clap::Args>` around, one can simply define a struct with all the options and let `clap` do the work for us, thanks to the `derive` macro. This creates a cleaner separation between the exporters and the magagement of the CLI. This will be useful for #50 and #145.
declaration:
```rust
fn get_options() -> Vec<clap::Arg> {
let mut options = Vec::new();
let arg = Arg::new("address")
.default_value(DEFAULT_IP_ADDRESS)
.help("Riemann ipv6 or ipv4 address. If mTLS is used then server fqdn must be provided")
.long("address")
.short('a')
.required(false)
.action(clap::ArgAction::Set);
options.push(arg);
let arg = Arg::new("port")
.default_value(DEFAULT_PORT) …
```
> Refactor exporter creation with clap v4

- helm/scaphandre/values.yaml
Hi @bpetit,
I found a problem with the dev branch and the --containers flag.
Removing the true value fixes it and I tested with both the dev and latest branches and it works with both. 
```
kubectl get pods
NAME               READY   STATUS             RESTARTS     AGE
scaphandre-v7wh6   0/1     CrashLoopBackOff   1 (3s ago)   5s
kubectl logs scaphandre-v7wh6
error: unexpected value 'true' for '--containers' found; no more were expected
Usage: scaphandre prometheus --containers
For more information, try '--help'.
```
> fix: Don't use value for --containers flag in chart

- .github/workflows/debian-release.yml
This pull request aims to add an automatic Debian package generation for the associated version tag through a GitHub Actions workflow. It will check the correct build of the package for Debian 11 ('bullseye') and 12 ('bookwork') and their installation on those distributions. It is built with the help of [barnumbirr's repository](https://github.com/barnumbirr/scaphandre-debian/).
> Create Debian package with version tag
